In [46]:
import numpy as np
BATCH_SIZE = 64

W1 = np.random.rand(784, 512)
W2 = np.random.rand(512, 512)
W3 = np.random.rand(512, 10)
b1 = np.random.rand(512)
b2 = np.random.rand(512)
b3 = np.random.rand(512)

X = array = np.random.randint(-1, 2, (BATCH_SIZE, 784))


Z1 = X @ W1
print("Z1 shape:", Z1.shape)

Y1 = np.maximum(Z1, 0)
print("Y1 shape:", Y1.shape)


Z2 = Y1 @ W2
print("Z2 shape:", Z2.shape)

Y2 = np.maximum(Z2, 0)
print("Y2 shape:", Y2.shape)


Z3 = Y2 @ W3
print("Z3 shape:", Z3.shape)

Y3 = np.exp(Z3)/np.sum(np.exp(Z3))
print("Y3 shape:", Y3.shape)

y_real = np.random.rand(BATCH_SIZE, 10)
y_pred = np.random.rand(BATCH_SIZE, 10)


#Градиенты на выходном слое
dZ3 = y_real - y_pred

Y2_exp = np.expand_dims(Y2, axis=2)  # (64, 512, 1)
dZ3_exp = np.expand_dims(dZ3, axis=1)  # (64, 1, 10)
dW3 = np.sum(Y2_exp @ dZ3_exp, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
db3 = np.sum(dZ3, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
print("dW3 shape:", dW3.shape)
print("db3 shape:", db3.shape)

dY2 = dZ3 @ W3.T


#Градиенты на втором скрытом слое
dZ2 = np.where(Z2 > 0, 1, 0) * dY2
print("dZ2 shape:", dZ2.shape)

Y1_exp = np.expand_dims(Y1, axis=2)  # (64, 512, 1)
dZ2_exp = np.expand_dims(dZ2, axis=1)  # (64, 1, 10)
dW2 = np.sum(Y1_exp @ dZ2_exp, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
db2 = np.sum(dZ2, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
print("dW2 shape:", dW2.shape)
print("db2 shape:", db2.shape)

dY1 = dZ2 @ W2.T

#Градиенты на первом скрытом слое
dZ1 = np.where(Z1 > 0, 1, 0) * dY1
print("dZ1 shape:", dZ1.shape)

X_exp = np.expand_dims(X, axis=2)  # (64, 512, 1)
dZ1_exp = np.expand_dims(dZ1, axis=1)  # (64, 1, 10)
dW1 = np.sum(X_exp @ dZ1_exp, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
db1 = np.sum(dZ1, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
print("dW1 shape:", dW1.shape)
print("db1 shape:", db1.shape)

dX = dZ1 @ W1.T




Z1 shape: (64, 512)
Y1 shape: (64, 512)
Z2 shape: (64, 512)
Y2 shape: (64, 512)
Z3 shape: (64, 10)
Y3 shape: (64, 10)
dW3 shape: (512, 10)
db3 shape: (10,)
dZ2 shape: (64, 512)
dW2 shape: (512, 512)
db2 shape: (512,)
dZ1 shape: (64, 512)


C:\Users\yuzia\AppData\Local\Temp\ipykernel_56712\1297876012.py:31: RuntimeWarning: overflow encountered in exp
  Y3 = np.exp(Z3)/np.sum(np.exp(Z3))
C:\Users\yuzia\AppData\Local\Temp\ipykernel_56712\1297876012.py:31: RuntimeWarning: invalid value encountered in divide
  Y3 = np.exp(Z3)/np.sum(np.exp(Z3))


dW1 shape: (784, 512)
db1 shape: (512,)


In [70]:
import numpy as np
BATCH_SIZE = 2

W1 = np.array([
    [2, 1],
    [0, 1],
    [3, 2],
    [1, 0],
])
W2 = np.array([
    [3, 4],
    [1, 2],
])
W3 = np.array([
    [2, 2, 2],
    [0, 1, 1],
])
b1 = np.array([1, 1, 1])
b2 = np.array([2, 2, 2])
b3 = np.array([3, 3, 3])

X = np.array([
    [.01, .02, .03, .04],
    [.01, .02, .03, .04]
])


Z1 = X @ W1
#print("Z1 shape:", Z1.shape)

Y1 = np.maximum(Z1, 0)
#print("Y1 shape:", Y1.shape)
print("Y1: ", Y1)

Z2 = Y1 @ W2
#print("Z2 shape:", Z2.shape)

Y2 = np.maximum(Z2, 0)
#print("Y2 shape:", Y2.shape)
print("Y2: ", Y2)

Z3 = Y2 @ W3
#print("Z3 shape:", Z3.shape)
print("Z3: ", Z3)

#print(np.sum(np.exp(Z3), 1))
Y3 = np.exp(Z3)/np.sum(np.exp(Z3), 1)[:, np.newaxis]
#print("Y3 shape:", Y3.shape)

y_real = np.array([
    [0, 0, 1],
    [1, 0, 0]
])
y_pred = Y3
print("y_real: ", y_real)
print("y_pred: ", y_pred)


#Градиенты на выходном слое
dZ3 = y_pred - y_real
print("dZ3: ", dZ3)

Y2_exp = np.expand_dims(Y2, axis=2)  # (64, 512, 1)
dZ3_exp = np.expand_dims(dZ3, axis=1)  # (64, 1, 10)
dW3 = np.sum(Y2_exp @ dZ3_exp, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
db3 = np.sum(dZ3, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
print("dW3 shape:", dW3.shape)
print("db3 shape:", db3.shape)
print("dW3:", dW3)
print("db3:", db3)

dY2 = dZ3 @ W3.T


#Градиенты на втором скрытом слое
dZ2 = np.where(Z2 > 0, 1, 0) * dY2
print("dZ2 shape:", dZ2.shape)

Y1_exp = np.expand_dims(Y1, axis=2)  # (64, 512, 1)
dZ2_exp = np.expand_dims(dZ2, axis=1)  # (64, 1, 10)
dW2 = np.sum(Y1_exp @ dZ2_exp, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
db2 = np.sum(dZ2, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
print("dW2 shape:", dW2.shape)
print("db2 shape:", db2.shape)
print("dW2:", dW2)
print("db2:", db2)

dY1 = dZ2 @ W2.T

#Градиенты на первом скрытом слое
dZ1 = np.where(Z1 > 0, 1, 0) * dY1
print("dZ1 shape:", dZ1.shape)

X_exp = np.expand_dims(X, axis=2)  # (64, 512, 1)
dZ1_exp = np.expand_dims(dZ1, axis=1)  # (64, 1, 10)
dW1 = np.sum(X_exp @ dZ1_exp, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
db1 = np.sum(dZ1, 0) / BATCH_SIZE  # Матрицное умножение → (64, 512, 10)
print("dW1 shape:", dW1.shape)
print("db1 shape:", db1.shape)
print("dW1:", dW1)
print("db1:", db1)

dX = dZ1 @ W1.T




Y1:  [[0.15 0.09]
 [0.15 0.09]]
Y2:  [[0.54 0.78]
 [0.54 0.78]]
Z3:  [[1.08 1.86 1.86]
 [1.08 1.86 1.86]]
y_real:  [[0 0 1]
 [1 0 0]]
y_pred:  [[0.18646473 0.40676764 0.40676764]
 [0.18646473 0.40676764 0.40676764]]
dZ3:  [[ 0.18646473  0.40676764 -0.59323236]
 [-0.81353527  0.40676764  0.40676764]]
dW3 shape: (2, 3)
db3 shape: (3,)
dW3: [[-0.16930905  0.21965452 -0.05034548]
 [-0.24455751  0.31727876 -0.07272124]]
db3: [-0.31353527  0.40676764 -0.09323236]
dZ2 shape: (2, 2)
dW2 shape: (2, 2)
db2 shape: (2,)
dW2: [[-3.33066907e-17  4.70302906e-02]
 [-1.99840144e-17  2.82181744e-02]]
db2: [-2.22044605e-16  3.13535271e-01]
dZ1 shape: (2, 2)
dW1 shape: (4, 2)
db1 shape: (2,)
dW1: [[0.01254141 0.00627071]
 [0.02508282 0.01254141]
 [0.03762423 0.01881212]
 [0.05016564 0.02508282]]
db1: [1.25414108 0.62707054]
